#Each new term in the Fibonacci sequence is generated by addding the previous two terms. By starting with 1 and 2, the first terms will be:
#					1,2,3,5,8,13,21,34,55,89,...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

timer_start = Time.now

total = 0
previous = 0
i = 1

while i< 4000000

  total+=i if (i%2 == 0)

  i , previous = previous,  previous+i

end

puts "Answer: #{total}."

puts "Elapsed time: #{(Time.now - timer_start)*1000} milliseconds"
